apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusternetworks.network.openshift.io
spec:
  group: network.openshift.io
  version: v1
  scope: Cluster
  names:
    kind: ClusterNetwork
    singular: clusternetwork
    plural: clusternetworks
  validation:
    openAPIV3Schema:
      properties:
        network:
          type: string
        hostsubnetlength:
          type: integer
          minimum: 0
        serviceNetwork:
          type: string
        pluginName:
          type: string
        clusterNetworks:
          type: array
          items:
            type: object
            properties:
              CIDR:
                type: string
              hostSubnetLength:
                type: integer
                minimum: 0
        vxlanPort:
          type: integer
          minimum: 1
          maximum: 65535
        mtu:
          type: integer
          minimum: 576
          maximum: 65536
  additionalPrinterColumns:
  - name: Cluster Network
    type: string
    description: The primary cluster network CIDR
    JSONPath: .network
  - name: Service Network
    type: string
    description: The service network CIDR
    JSONPath: .serviceNetwork
  - name: Plugin Name
    type: string
    description: The OpenShift SDN network plug-in in use
    JSONPath: .pluginName
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hostsubnets.network.openshift.io
spec:
  group: network.openshift.io
  version: v1
  scope: Cluster
  names:
    kind: HostSubnet
    singular: hostsubnet
    plural: hostsubnets
  validation:
    openAPIV3Schema:
      properties:
        host:
          type: string
          pattern: '^[a-z0-9.-]+$'
        hostIP:
          type: string
        subnet:
          type: string
        egressIPs:
          type: array
          items:
            type: string
        egressCIDRs:
          type: array
          items:
            type: string
  additionalPrinterColumns:
  - name: Host
    type: string
    description: The name of the node
    JSONPath: .host
  - name: Host IP
    type: string
    description: The IP address to be used as a VTEP by other nodes in the overlay network
    JSONPath: .hostIP
  - name: Subnet
    type: string
    description: The CIDR range of the overlay network assigned to the node for its pods
    JSONPath: .subnet
  - name: Egress CIDRs
    type: string
    description: The network egress CIDRs
    JSONPath: .egressCIDRs
  - name: Egress IPs
    type: string
    description: The network egress IP addresses
    JSONPath: .egressIPs
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: netnamespaces.network.openshift.io
spec:
  group: network.openshift.io
  version: v1
  scope: Cluster
  names:
    kind: NetNamespace
    singular: netnamespace
    plural: netnamespaces
  validation:
    openAPIV3Schema:
      properties:
        netname:
          type: string
          pattern: '^[a-z0-9.-]+$'
        netid:
          type: integer
          minimum: 0
          maximum: 16777215
        egressIPs:
          type: array
          items:
            type: string
  additionalPrinterColumns:
  - name: NetID
    type: integer
    description: The network identifier of the network namespace
    JSONPath: .netid
  - name: Egress IPs
    type: string
    description: The network egress IP addresses
    JSONPath: .egressIPs
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: egressnetworkpolicies.network.openshift.io
spec:
  group: network.openshift.io
  version: v1
  scope: Namespaced
  names:
    kind: EgressNetworkPolicy
    singular: egressnetworkpolicy
    plural: egressnetworkpolicies
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            egress:
              type: array
              maxItems: 50
              items:
                type: object
                properties:
                  type:
                    type: string
                    pattern: '^Allow|Deny$'
                  to:
                    type: object
                    minProperties: 1
                    maxProperties: 1
                    properties:
                      cidrSelector:
                        type: string
                      dnsName:
                        type: string
